import {
    Search,
    Users,
    FileText,
    MessageSquare,
    BarChart3,
    Shield,
    Clock,
    Award,
    Briefcase,
    Building2,
    LayoutDashboard,
    Plus
} from 'lucide-react';

export const jobSeekerFeatures = [
    {
        icon: Search,
        title: "Smart Job Matching",
        description: "AI-powered algorithm matches you with relevant opportunities based on your skills and preferences."
    },
    {
        icon: FileText,
        title: "Resume Builder",
        description: "Create professional resumes with our intuitive builder and templates designed by experts."
    },
    {
        icon: MessageSquare,
        title: "Direct Communication",
        description: "Connect directly with hiring managers and recruiters through our secure messaging platform."
    },
    {
        icon: Award,
        title: "Skill Assessment",
        description: "Showcase your abilities with verified skill tests and earn badges that employers trust."
    },
]

export const employerFeatures = [
    {
        icon: Users,
        title: "Talent Pool Access",
        description: "Access our vast database of pre-screened candidates and find the perfect fit for your team."
    },
    {
        icon: BarChart3,
        title: "Analytics Dashboard",
        description: "Track your hiring performance with detailed analytics and insights on candidate engagement."
    },
    {
        icon: Shield,
        title: "Verified Candidates",
        description: "All candidates undergo background verification to ensure you're hiring trustworthy professionals."
    },
    {
        icon: Clock,
        title: "Quick Hiring",
        description: "Streamlined hiring process reduces time-to-hire by 60% with automated screening tools."
    },
];

// Navigation items configuration
export const NAVIGATION_MENU = [
    { id: "employer-dashboard", name: "Dashboard", icon: LayoutDashboard },
    { id: "post-job", name: "Post Job", icon: Plus },
    { id: "manage-jobs", name: "Manage Jobs", icon: Briefcase },
    { id: "company-profile", name: "Company Profile", icon: Building2 },
];

// Categories and job types
export const CATEGORIES = [
    { value: "Engineering", label: "Engineering" },
    { value: "Design", label: "Design" },
    { value: "Marketing", label: "Marketing" },
    { value: "Sales", label: "Sales" },
    { value: "IT & Software", label: "IT & Software" },
    { value: "Customer-service", label: "Customer Service" },
    { value: "Product", label: "Product" },
    { value: "Operations", label: "Operations" },
    { value: "Finance", label: "Finance" },
    { value: "HR", label: "Human Resources" },
    { value: "Other", label: "Other" },
];

// job types
export const JOB_TYPES = [
    { value: "Remote", label: "Remote" },
    { value: "Full-Time", label: "Full-Time" },
    { value: "Part-Time", label: "Part-Time" },
    { value: "Contract", label: "Contract" },
    { value: "Internship", label: "Internship" },
]

export const SALARY_RANGES = [
    "Less that $1000",
    "$1000 - $15,000",
    "More than $15,000"
]
export const SKILLS = [
    // Languages
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C",
    "C++",
    "CSharp",
    "Go",
    "Rust",
    "PHP",
    "Ruby",
    "Kotlin",
    "Swift",
    "Dart",
    "Scala",
    "Elixir",
    "ObjectiveC",
    "R",

    // Frontend
    "HTML",
    "CSS",
    "Sass",
    "SCSS",
    "TailwindCSS",
    "Bootstrap",
    "MaterialUI",
    "ChakraUI",
    "ShadcnUI",
    "ReactJS",
    "NextJS",
    "VueJS",
    "NuxtJS",
    "Angular",
    "Svelte",
    "Redux",
    "ReduxToolkit",
    "Zustand",
    "ReactQuery",
    "TanStackQuery",
    "Apollo",
    "RESTAPI",
    "WebSocket",
    "SocketIO",
    "FramerMotion",

    // Backend
    "NodeJS",
    "ExpressJS",
    "NestJS",
    "Django",
    "FastAPI",
    "Flask",
    "SpringBoot",
    "ASP.NETCore",
    "Laravel",
    "RubyOnRails",
    "Phoenix",
    "Gin",
    "Fiber",
    "Echo",
    "Actix",
    "Rocket",
    "Quarkus",
    "Micronaut",
    "gRPC",
    "GraphQL",

    // Mobile Development
    "ReactNative",
    "Flutter",
    "Ionic",
    "Xamarin",
    "Expo",

    // Databases
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "SQLite",
    "Redis",
    "OracleDB",
    "MariaDB",
    "Cassandra",
    "DynamoDB",
    "Neo4j",
    "Elasticsearch",
    "OpenSearch",
    "Snowflake",
    "Google BigQuery",
    "Amazon Redshift",
    "Databricks",

    // ORMs
    "Mongoose",
    "Prisma",
    "DrizzleORM",
    "TypeORM",
    "Sequelize",
    "Hibernate",
    "Entity Framework",

    // Cloud
    "AWS",
    "Azure",
    "GCP",
    "Firebase",
    "Supabase",
    "Vercel",
    "Netlify",
    "Cloudflare",
    "DigitalOcean",
    "Heroku",
    "Render",

    // DevOps
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "Helm",
    "ArgoCD",
    "Jenkins",
    "GitHubActions",
    "GitLab CI",
    "CircleCI",
    "TravisCI",
    "Linux",
    "Bash",
    "Nginx",
    "Apache",
    "Prometheus",
    "Grafana",
    "Kafka",
    "RabbitMQ",
    "NATS",
    "Apache Pulsar",

    // DevSecOps
    "Snyk",
    "Trivy",
    "SonarQube",
    "Aqua Security",
    "Prisma Cloud",
    "Falco",
    "HashiCorp Vault",
    "Checkov",
    "Open Policy Agent",
    "Cosign",
    "Sigstore",
    "Anchore",
    "Dependabot",

    // Cybersecurity
    "Kali Linux",
    "Metasploit",
    "Wireshark",
    "Nmap",
    "Burp Suite",
    "OWASP ZAP",
    "Nessus",
    "Snort",
    "Suricata",
    "Splunk",
    "Microsoft Defender",
    "CrowdStrike",
    "SentinelOne",
    "IBM QRadar",
    "Microsoft Sentinel",
    "OpenVAS",
    "John the Ripper",
    "Hashcat",
    "Autopsy",
    "FTK",
    "Volatility",

    // Version Control
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",

    // Authentication & Security
    "JWT",
    "OAuth",
    "OAuth2",
    "OpenIDConnect",
    "AuthJS",
    "Clerk",
    "Keycloak",
    "Firebase Authentication",
    "Supabase Auth",

    // Testing / QA
    "Jest",
    "Vitest",
    "Mocha",
    "Chai",
    "Cypress",
    "Playwright",
    "Selenium",
    "Postman",
    "Insomnia",
    "JUnit",
    "TestNG",
    "PyTest",
    "Robot Framework",
    "SoapUI",
    "JMeter",
    "BrowserStack",
    "LambdaTest",
    "Appium",
    "Katalon Studio",
    "TestRail",
    "Xray",

    // AI / Machine Learning
    "MachineLearning",
    "TensorFlow",
    "PyTorch",
    "ScikitLearn",
    "Pandas",
    "Apache Spark",
    "HuggingFace",
    "OpenAI",
    "LangChain",
    "LlamaIndex",
    "PromptEngineering",
    "Jupyter Notebook",
    "Google Colab",
    "Ollama",
    "MLflow",

    // UI / UX
    "Figma",
    "Adobe XD",
    "Sketch",
    "Framer",
    "Miro",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Maze",
    "Canva",
    "User Research",
    "Wireframing",
    "Prototyping",
    "Design Systems",
    "Interaction Design",
    "Responsive Design",
    "Accessibility",

    // Marketing
    "Google Analytics",
    "Google Ads",
    "Meta Ads Manager",
    "LinkedIn Campaign Manager",
    "Google Tag Manager",
    "SEMrush",
    "Ahrefs",
    "HubSpot Marketing Hub",
    "Mailchimp",
    "Hootsuite",
    "Buffer",
    "Google Search Console",
    "TikTok Ads Manager",

    // Sales
    "Salesforce",
    "HubSpot CRM",
    "Zoho CRM",
    "Pipedrive",
    "LinkedIn Sales Navigator",
    "Apollo.io",
    "ZoomInfo",
    "Calendly",
    "DocuSign",
    "Outreach",
    "Gong",
    "Salesloft",

    // HR
    "Workday",
    "BambooHR",
    "SAP SuccessFactors",
    "ADP Workforce Now",
    "Greenhouse",
    "Lever",
    "Workable",
    "Lattice",
    "Culture Amp",
    "LinkedIn Recruiter",
    "iCIMS",
    "Docebo",
    "TalentLMS",

    "Microsoft Word",
    "Microsoft Excel",
    "Microsoft PowerPoint",
    "Microsoft Outlook",
    "Microsoft Teams",
    "Google Workspace",
    "Google Docs",
    "Google Sheets",
    "Google Drive",
    "Zoom",
    "Adobe Acrobat",
    "DocuSign",
    "OneDrive",
    "QuickBooks",

    // Operations
    "Asana",
    "Trello",
    "Monday.com",
    "ClickUp",
    "Notion",
    "Confluence",
    "Airtable",

    // Data analytics
    "SQL",
    "Power BI",
    "Looker",
    "dbt",
    "NumPy",

    // Business Analysis
    "Tableau",
    "Jira",
    "Lucidchart",
    "Microsoft Visio",
    "Requirement Gathering",
    "Stakeholder Management",

    // Product Manager
    "Amplitude",
    "Mixpanel",
    "Hotjar",
    "Productboard",
    "Aha!",
    "Roadmapping",
    "User Stories",

    // Accounting & Finance
    "Xero",
    "Sage",
    "SAP ERP",
    "Oracle NetSuite",
    "Zoho Books",
    "Financial Reporting",
    "Budgeting",

    // CMS & Ecommerce
    "WordPress",
    "Shopify",
    "WooCommerce",
    "Magento",
    "Webflow",
    "Contentful",
    "Strapi",
    "Sanity",

    // Architecture & Methodologies
    "Agile",
    "Scrum",
    "Kanban",
    "Lean",
    "TDD",
    "BDD",
    "DDD",
    "Microservices",
    "System Design",
    "REST APIs",
    "CI/CD",
    "Design Patterns",
    "SOLID Principles",

    // Soft skills
    "Communication",
    "Teamwork",
    "Leadership",
    "Problem Solving",
    "Critical Thinking",
    "Time Management",
    "Adaptability",
    "Decision Making",
    "Negotiation",
    "Presentation Skills",
    "Emotional Intelligence",
    "Creativity"
];